- hosts: awsvm
  tasks:
   - name: Download docker.repo to configire yum for docker
     get_url:
       url: "https://download.docker.com/linux/rhel/docker-ce.repo"
       dest: "/etc/yum.repos.d/"

   - name: Long form task does not
     replace:
       path: "/etc/yum.repos.d/docker-ce.repo"
       regexp: 'rhel'
       replace: 'centos'

   - name: install docker-ce software
     package:                              
       name: "docker-ce"
       state: present

   - name: Start Docker Service
     service:
       name: "docker"
       state: started

   - name: i need pip3 command install respective software
     package:
       name: "python38-pip"
       state: present

   - name: Install docker py python SDK
     pip:
        name: "docker-py"


   - name: pull docker images named ubuntu
     docker_image:
       name: ubuntu
       tag: 14.04

   - name: Container of ubuntu
     docker_container:
       name: myvimalc1
       state: started
       image: ubuntu:14.04
       command: sleep infinity
       

