- hosts: localhost
  vars_files:
  - pass.yml
  tasks:
  - name: Sending an e-mail using Gmail SMTP servers
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ myuser }}"
      password: "{{ mypass }}"
      to: durantapatra.dp.dp@gmail.com
      subject: Ansible Test Email by Localhost CN
      body: System {{ ansible_hostname }} has been successfully provisioned.
   # delegate_to: localhost
